services:
  #  urlshortner.api:
  #    image: urlshortner.api
  #    build:
  #      context: .
  #      dockerfile: src/UrlShortner.Api/Dockerfile
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
